### PR TITLE
Update to Qt 5.15.0

### PR DESCRIPTION
**Pull request by shuffle2**
* Update to Qt 5.15.0
* Enable accessibility feature (fixes https://bugs.dolphin-emu.org/issues/12014 )
* Change readme to markdown (makes link to qsc more obvious)

### CODE REVIEW

**Comment by AdmiralCurtiss** [comment]
Dolphin seems to build and run fine with this, on x86-64 anyway.

**Comment by shuffle2** [comment]
I tested on arm64 and it runs fine as well (including narrator).

However, I've noticed on the arm64 system that the UI is larger than my older build of dolphin I had on that system.
I use 150% scaling on that screen, while my x64 system just uses 100% scaling. Is this an expected difference from the Qt upgrade? Do we need look into this / any idea what's going on?

(tagging @spycrab )

**Comment by shuffle2** [comment]
After some fiddling, I've determined it's now actually working as expected, so maybe we can say that's another benefit of updating Qt :)

Here is older dolphin compared to current master built with Qt 5.15.0 with 300% scaling (to exaggerate the difference):
Annotation 2020-08-16 161944

**Comment by shuffle2** [comment]
https://lists.qt-project.org/pipermail/releasing/2020-August/002782.html
Release target for 5.15.1 is on the 20th (~3days from now). So perhaps waiting is fine ... 😠 I can update this PR then, but **_please_** merge it ASAP, afterwards.

It seems like there will be no meaningful updates to Qt5 after 5.15.1 - it is judged to be stable.
Perhaps post-5.15.1 will be a good time to create a new Qt repo for dolphin (e.g. "ext-win-qt6" for Qt6), to prevent needing to carry the complete history around.

**Comment by spycrab** [comment]
@shuffle2 Oh I was under the impression that you were actually able to merge it (and from our IRC conversation that you were able to do so). But yes I can merge that once you've updated it.

**Comment by shuffle2** [comment]
@spycrab i just realized (as i was debugging dolphin..) there is:
```yaml
delete_regex:
        - .*\.pdb
```
...I assume it will be fine if I just remove this (add pdbs) for this ext-win-qt repo?

**Comment by shuffle2** [comment]
https://lists.qt-project.org/pipermail/releasing/2020-August/002783.html 
5.15.1 has been delayed without a target date given 😠

**Comment by AdmiralCurtiss** [comment]
IMO just merge this then.

**Comment by spycrab** [comment]
@shuffle2 FWIW the branch has happened now. https://lists.qt-project.org/pipermail/development/2020-August/040115.html

**Comment by lioncash** [comment]
We can always update to 5.15.1 at any point when it releases. As far as I've read, there's no actual hard blocker that was pointed out. Because of that, I'm OK with merging this as is, since it resolves a long-standing problem with the main code base being built out of the box without any workarounds as well as an issue on the tracker.

**Pull request merged**
