### PR TITLE
Update to Qt5.15.0

### PR DESCRIPTION
**Pull request by AdmiralCurtiss**
Disclaimer: I have no idea if I did this right. It seems to work for building Dolphin though, at least on x64.

My process was roughly this:
- Cloned https://github.com/spycrab/qsc.git
- Copied https://github.com/dolphin-emu/ext-win-qt/blob/29bee719d7cb6e2894c62b4ce53c6fc9f966faf7/Qt5.14.1/dolphin-amd64.yml and https://github.com/dolphin-emu/ext-win-qt/blob/29bee719d7cb6e2894c62b4ce53c6fc9f966faf7/Qt5.14.1/dolphin-arm64.yml, changing a few lines near the top as appropriate (you can see the modified files in this PR, but: changed Qt version, and changed the path in the ARM file).
- Downloaded the Qt source code zip from https://download.qt.io/archive/qt/5.15/5.15.0/single/ and placed it at `qsc/archives/qt-everywhere-src-5.15.0.zip`
- Ran the qsc python script first on the amd64 manifest, and then on the arm64 manifest.

The thing I'm unsure of in particular is whether I needed to adjust the manifest files further to enable/disable features (are there any new features that need to be turned off for GPL software, for example?) or adjust the files that are actually used for Dolphin. There doesn't seem to be any documentation on how this particular set of rules was conceived...

### CODE REVIEW

**Comment by shuffle2** [comment]
funny, i didnt bother to check the PRs here until after making mine.

Do you have any idea if the changes in #12 are needed?

fwiw, I made a PR to qsc which makes it a bit easier to "just use", dont need to manually download suff: https://github.com/spycrab/qsc/pull/1

In any case, we should merge 5.15.0 ASAP. Broken dolphin build for so long is insane.

**Comment by spycrab** [comment]
> In any case, we should merge 5.15.0 ASAP. Broken dolphin build for so long is insane.

Is it broken beyond the screen reader feature?

> Do you have any idea if the changes in #12 are needed?

Not fixing it shouldn't break anything rn FWIW

**Comment by spycrab** [comment]
Any release we use should probably be built without disabling the accessibility feature.

Which means this
```yml
feature:
...
  - accessibility: false
```

probably has to be removed.

**Comment by AdmiralCurtiss** [comment]
> > In any case, we should merge 5.15.0 ASAP. Broken dolphin build for so long is insane.
> 
> Is it broken beyond the screen reader feature?

On Windows using an up-to-date Visual Studio 2019, yes it is without modifying either the Qt headers or forcing the build to C++17. Has been for months. It's quite annoying!

**Comment by spycrab** [comment]
Ah yes, I knew I forgot a part of it. Well anyway, if we're updating it we might as well fix the screen reader issue as well. It also seems that you didn't include new yml files in your build. Apart from that it looks okay for me if we don't wanna wait for 5.15.1 (should release this month IIRC).

**Comment by shuffle2** [comment]
I updated #14 and tested that it fixes screen reader (tested with windows narrator).

**Comment by AdmiralCurtiss** [comment]
Alright, should probably go with #14 then.

**Pull request closed without merging**
