### PR TITLE
Update to Qt6.3.0

### PR DESCRIPTION
**Pull request by shuffle2**
see https://github.com/dolphin-emu/dolphin/pull/10559

### CODE REVIEW

**Comment by shuffle2** [comment]
@lioncash poke?

**Comment by AdmiralCurtiss** [comment]
Running a debug build of Dolphin (using the linked PR) with this breaks with

~~~
Unhandled exception at 0x00007FFAACC14F69 in DolphinD.exe: Microsoft C++ exception: std::__non_rtti_object at memory location 0x0000005F06D9D078.
~~~

followed by

~~~
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Error!

Program: Qt6Cored.dll
Module: 6.3.0
File: E:\qsc\6.3.0_dolphin.x64.build\qtbase\include\QtCore\../../../../qt-everywhere-src-6.3.0/qtbase/src/corelib/kernel/qobjectdefs_impl.h
Line: 156

ASSERT failure in QActionGroup: "Called object is not of the correct type (class destructor may have already run)", file E:\qsc\6.3.0_dolphin.x64.build\qtbase\include\QtCore\../../../../qt-everywhere-src-6.3.0/qtbase/src/corelib/kernel/qobjectdefs_impl.h, line 156

(Press Retry to debug the application)

---------------------------
Abort   Retry   Ignore   
---------------------------
~~~

(at `action->setActionGroup(m_state_slots);` in `void MenuBar::AddStateSlotMenu(QMenu* emu_menu)`)

I'm not really sure where this comes from. We do build Dolphin without RTTI, but as far as I'm aware Qt shouldn't be using that anyway?

**Comment by AdmiralCurtiss** [comment]
(fwiw I'm not really sure *why* we disable RTTI in Dolphin, nor where in the build files it is set like that)

**Comment by shuffle2** [comment]
Thanks for testing. That’s odd as I’ve tried debug dolphin build as well. I’ll have to retry and fiddle around. Are you using the new build with old dolphin config files? Can you test if you still see that error after clearing out dolphin config + dolphin directory? If that makes it go away can you send config infos?

**Comment by AdmiralCurtiss** [comment]
For reference, RTTI flag is here: https://github.com/dolphin-emu/dolphin/blob/3172199d3396da5ff08682dab526868807e7d50a/Source/VSProps/Base.props#L92

Enabling that does fix the problem, though I'd rather figure out why I'm running into this in the first place...

**Comment by shuffle2** [comment]
Yea.. we’re not going to enable rtti 😛

**Comment by AdmiralCurtiss** [comment]
Happens even with a fresh userdir.

I dug out the relevant function in the Qt6.3 sources:

~~~
    template<typename Obj> inline void assertObjectType(QObject *o)
    {
        // ensure all three compile
        [[maybe_unused]] auto staticcast = [](QObject *obj) { return static_cast<Obj *>(obj); };
        [[maybe_unused]] auto qobjcast = [](QObject *obj) { return Obj::staticMetaObject.cast(obj); };
#ifdef __cpp_rtti
        [[maybe_unused]] auto dyncast = [](QObject *obj) { return dynamic_cast<Obj *>(obj); };
        auto cast = dyncast;
#else
        auto cast = qobjcast;
#endif
        Q_ASSERT_X(cast(o), Obj::staticMetaObject.className(),
                   "Called object is not of the correct type (class destructor may have already run)");
    }
~~~

Does MSVC set `__cpp_rtti` even if RTTI is off?

**Comment by AdmiralCurtiss** [comment]
Nope, `__cpp_rtti` is definitely undefined when building Dolphin.

Oh, you know what probably happened here? Did you build *Qt itself* here with RTTI enabled?

**Comment by shuffle2** [comment]
I’ve used whatever qt defaults to for rtti setting. The qt meta object concept was essentially rtti created by qt before c++ rtti existed (rtti shouldn’t be required for this assert to fire, so if rtti is enabled in qt build or not would seem to be inconsequential). Can you paste the call stack of this assert.

**Comment by AdmiralCurtiss** [comment]
Well I don't have the Qt symbols, so I'm not sure how useful it is.

The exception:

~~~
 	KernelBase.dll!00007ffaacc14f69()	Unknown
 	vcruntime140d.dll!00007ffa8c59b460()	Unknown
 	vcruntime140d.dll!00007ffa8c59a833()	Unknown
 	Qt6Guid.dll!00007ffa3a40bc11()	Unknown
 	Qt6Guid.dll!00007ffa3a40a6db()	Unknown
 	Qt6Guid.dll!00007ffa3a40c31e()	Unknown
 	Qt6Guid.dll!00007ffa3a40a758()	Unknown
 	Qt6Guid.dll!00007ffa3a40d062()	Unknown
 	Qt6Cored.dll!00007ffa3dc96943()	Unknown
 	Qt6Cored.dll!00007ffa3dd1fad8()	Unknown
 	Qt6Cored.dll!00007ffa3dd0b3c8()	Unknown
 	Qt6Guid.dll!00007ffa3a4059e2()	Unknown
 	Qt6Guid.dll!00007ffa3a406f66()	Unknown
 	Qt6Guid.dll!00007ffa3a403bbf()	Unknown
>	DolphinD.exe!MenuBar::AddStateSlotMenu(QMenu * emu_menu) Line 372	C++
 	DolphinD.exe!MenuBar::AddEmulationMenu() Line 323	C++
 	DolphinD.exe!MenuBar::MenuBar(QWidget * parent) Line 79	C++
 	DolphinD.exe!MainWindow::CreateComponents() Line 411	C++
 	DolphinD.exe!MainWindow::MainWindow(std::unique_ptr<BootParameters,std::default_delete<BootParameters>> boot_parameters, const std::string & movie_path) Line 221	C++
 	DolphinD.exe!app_main(int argc, char * * argv) Line 248	C++
 	DolphinD.exe!wWinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, wchar_t * __formal, int __formal) Line 310	C++
 	[External Code]	
~~~

The assert:

~~~
 	Qt6Cored.dll!00007ffa3db7fcd4()	Unknown
 	Qt6Cored.dll!00007ffa3db7d848()	Unknown
 	Qt6Cored.dll!00007ffa3db6b3ee()	Unknown
 	Qt6Guid.dll!00007ffa3a40a70c()	Unknown
 	Qt6Guid.dll!00007ffa3a40c31e()	Unknown
 	Qt6Guid.dll!00007ffa3a40a758()	Unknown
 	Qt6Guid.dll!00007ffa3a40d062()	Unknown
 	Qt6Cored.dll!00007ffa3dc96943()	Unknown
 	Qt6Cored.dll!00007ffa3dd1fad8()	Unknown
 	Qt6Cored.dll!00007ffa3dd0b3c8()	Unknown
 	Qt6Guid.dll!00007ffa3a4059e2()	Unknown
 	Qt6Guid.dll!00007ffa3a406f66()	Unknown
 	Qt6Guid.dll!00007ffa3a403bbf()	Unknown
>	DolphinD.exe!MenuBar::AddStateSlotMenu(QMenu * emu_menu) Line 372	C++
 	DolphinD.exe!MenuBar::AddEmulationMenu() Line 323	C++
 	DolphinD.exe!MenuBar::MenuBar(QWidget * parent) Line 79	C++
 	DolphinD.exe!MainWindow::CreateComponents() Line 411	C++
 	DolphinD.exe!MainWindow::MainWindow(std::unique_ptr<BootParameters,std::default_delete<BootParameters>> boot_parameters, const std::string & movie_path) Line 221	C++
 	DolphinD.exe!app_main(int argc, char * * argv) Line 248	C++
 	DolphinD.exe!wWinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, wchar_t * __formal, int __formal) Line 310	C++
 	[External Code]	
~~~

**Comment by AdmiralCurtiss** [comment]
(I can compile Qt myself for the symbols, if that helps.)

**Comment by shuffle2** [comment]
I have the symbols for this build saved, unfortunately I’m afk atm, I can send them to you in a few hours. I would guess whatever dolphin code is last on the stack before qt is the culprit tho.

**Comment by AdmiralCurtiss** [comment]
> (rtti shouldn’t be required for this assert to fire, so if rtti is enabled in qt build or not would seem to be inconsequential)

But it changes how the assert is evaluated. If `__cpp_rtti` is set it uses `dynamic_cast`, otherwise it uses `Obj::staticMetaObject.cast`.

**Comment by shuffle2** [comment]
> ```
> Unhandled exception at 0x00007FFAACC14F69 in DolphinD.exe: Microsoft C++ exception: std::__non_rtti_object at memory location 0x0000005F06D9D078.
> ```

Somehow I totally missed this part of your comment, and thought the assert in Qt source code was firing, but I realized it once I tried and saw it myself...

I've put some comments here: https://bugreports.qt.io/browse/QTBUG-98905?focusedCommentId=657946&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-657946

Basically, I had previously compiled and tested debug build of Qt6.2.4 , which didn't have this dynamic_cast of an object passed from dolphin.exe into the Qt DLL, so there was no assert. I will wait a little and see if Qt devs make some enlightening response, but either way I'll update this PR with RTTI disabled.

**Comment by shuffle2** [comment]
opened bug on Qt to see what they say: https://bugreports.qt.io/browse/QTBUG-102804

**Comment by AdmiralCurtiss** [comment]
So what I'm gathering from this, Qt6 requires RTTI now, on both sides since it casts objects created on the user's side? That kinda sucks.

**Comment by shuffle2** [comment]
yes it does suck. the easiest way forward is to enable RTTI only on the DolphinQt library (since it has types inheriting from QObject which will be dynamic_casted by Qt-internal code). The better way would be to fix Qt as they suggest, but tbh I don't feel like dealing with it.

**Comment by shuffle2** [comment]
I've updated the Qt6 PR on dolphin to enable RTTI only on DolphinQt project, and Debug build is working without that assert. You can test it again if you like..

**Comment by AdmiralCurtiss** [comment]
Yes, can confirm that I'm no longer getting asserts.

**Pull request merged**
