### PR TITLE
Update to Qt5.15.2

### PR DESCRIPTION
**Pull request by dreamsyntax**
* use VS2022 for AMD64
* updates to Qt5.15.2 to resolve the bug described here:
https://youtu.be/nSQotRmMWJ0
* Note: Don't merge yet, only includes x64, need help with ARM64
For whoever can compile on ARM64: VS2022 uses the included developer console environments now, and does not respect the `vcvarsall` attribute in the `.yaml`. Be sure to use the Native ARM x64 variant. I used "x64 Native Tools Command Prompt for VS 2022"

Detail written explanation in the discord, will also be added to the Dolphin PR.

I'll need help compiling for ARM64. In my testing AMD64 worked as expected.
If there's a preferred runner to build it rather than trusting me, I'm fine with that too.

### CODE REVIEW

**Comment by dreamsyntax** [comment]
Talked with @AdmiralCurtiss , we will use 5.15.3 since the commercial license restriction seems to be dropped.
They will also compile the AMD64 and ARM64 variants of 5.15.3
This PR will close with a reference to their variant

**Comment by dreamsyntax** [comment]
If for some reason 5.15.3 is determined to not be safe to merge (licensing concern or w/e) we can go with this PR.
#17 is now open, I'll leave this PR open until that is merged in. When it is merged I'll close this.

**Comment by shuffle2** [comment]
thanks! as i indicated on the dolphin pr, i'd prefer to just jump to Qt6.x (we've been waiting over a year already, so a couple more weeks doesn't seem like a huge deal to me... :)). but, maybe you want to try locally in the meantime with Qt6 and make sure the bug is actually fixed there too?
i'll probably work on updating qsc for qt6 within the next couple weeks anyway (if you just want to wait and download a build, then)

**Comment by dreamsyntax** [comment]
I'm just going to close this now. Sounds like a plan

**Comment by shuffle2** [comment]
@dreamsyntax fwiw i've built dolphin against qt6 here if you want to try  https://drive.google.com/file/d/1HjVGe-q4SHeOCn8JPCdj8pq7u0kJO7QM/view?usp=sharing

**Comment by dreamsyntax** [comment]
Confirmed the Qt6 build does not have the bug.
I did notice Qt6 conforms to Windows scaling, looks a bit funky. Details here:
https://github.com/dolphin-emu/dolphin/pull/10546#issuecomment-1086663371

**Pull request closed without merging**
