### PR TITLE
Update Qt to 5.7

### PR DESCRIPTION
**Pull request by ghost**
As the title says, it update the Qt to 5.7,
Note: The dolphin-emu repository will need a PR that changes the QtCompile.props to be able to build the DolphinQt2 project.

### CODE REVIEW

**Comment by shuffle2** [comment]
(oops)...i will look later

**Comment by ghost** [comment]
I Tested the Qt 5.7 submodule with DolphinQt2, it works fine
Note: I dont tested the gc/wii games, but it should run fine

**Comment by JosJuice** [comment]
How come this PR just seems to delete everything?

**Comment by ghost** [comment]
Strange, it should include Qt5.7, i will try to fix it

**Comment by ghost** [comment]
Oh, it includes Qt5.7, but since the commit is giant, Github can't show the entire commit

**Pull request closed without merging**
